create extension if not exists pgcrypto;

create table if not exists public.gifts (
  id bigint generated by default as identity primary key,
  name varchar(80) not null,
  message varchar(160) not null default 'دوستت دارم',
  personal_message varchar(240),
  image_key varchar(512),
  color varchar(7) not null,
  theme varchar(10) not null check (theme in ('light', 'dark')),
  token varchar(48) not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz
);

create table if not exists public.birthday_contents (
  owner varchar(32) primary key,
  cat_text varchar(160) not null,
  cake_text varchar(160) not null,
  motor_text varchar(160) not null,
  cat_image_key varchar(512),
  cake_image_key varchar(512),
  motor_image_key varchar(512),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_config (
  id integer primary key check (id = 1),
  password_hash varchar(200) not null,
  gift_password_hash varchar(200) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.gift_visits (
  id bigint generated by default as identity primary key,
  gift_id bigint not null references public.gifts(id) on delete cascade,
  opened_at timestamptz not null default now()
);

create table if not exists public.gift_unlock_sessions (
  id bigint generated by default as identity primary key,
  token_hash varchar(128) not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_sessions (
  id bigint generated by default as identity primary key,
  token_hash varchar(128) not null unique,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists gift_visits_gift_id_idx on public.gift_visits(gift_id);
create index if not exists gifts_expires_at_idx on public.gifts(expires_at);

alter table public.gifts enable row level security;
alter table public.birthday_contents enable row level security;
alter table public.admin_config enable row level security;
alter table public.gift_visits enable row level security;
alter table public.gift_unlock_sessions enable row level security;
alter table public.admin_sessions enable row level security;

insert into storage.buckets (id, name, public)
values ('gift-media', 'gift-media', true)
on conflict (id) do update set public = excluded.public;
