create table if not exists public.gift_link_events (
  id bigint generated by default as identity primary key,
  gift_id bigint not null references public.gifts(id) on delete cascade,
  event_type varchar(16) not null check (event_type in ('created', 'opened')),
  source_ip text,
  ip_fingerprint varchar(128),
  city varchar(128),
  region varchar(128),
  country varchar(128),
  browser varchar(64),
  operating_system varchar(64),
  device varchar(32),
  created_at timestamptz not null default now()
);

create index if not exists gift_link_events_gift_created_idx on public.gift_link_events(gift_id, created_at desc);
create index if not exists gift_link_events_created_at_idx on public.gift_link_events(created_at);

alter table public.gift_link_events enable row level security;
revoke all on table public.gift_link_events from anon, authenticated;
