alter table public.gifts
  add column if not exists experience varchar(16) not null default 'gift' check (experience in ('gift', 'birthday')),
  add column if not exists birthday_age smallint check (birthday_age between 0 and 99),
  add column if not exists birthday_cake_key varchar(512),
  add column if not exists birthday_has_builtin_candles boolean not null default false;

create table if not exists public.birthday_cake_presets (
  id bigint generated by default as identity primary key,
  slug varchar(64) not null unique,
  label varchar(100) not null,
  image_key varchar(512) not null,
  has_builtin_candles boolean not null default false,
  sort_order smallint not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists gifts_experience_idx on public.gifts(experience);
create index if not exists birthday_cake_presets_active_idx on public.birthday_cake_presets(is_active, sort_order);

alter table public.birthday_cake_presets enable row level security;
